# Generated by Django 5.0 on 2024-09-30 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(blank=True, max_length=80, null=True)),
                ('user_auth_provider', models.CharField(choices=[('Internal', 'Internal'), ('Facebook', 'Facebook'), ('iOS', 'Ios'), ('Google', 'Google')], default='Internal', max_length=20)),
                ('user_auth_provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name_api', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.FloatField(default=0)),
                ('product_stock', models.IntegerField(default=0)),
                ('product_image', models.CharField(max_length=255)),
                ('product_width', models.FloatField(default=0)),
                ('product_height', models.FloatField(default=0)),
                ('product_thickness', models.FloatField(default=0)),
                ('product_material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recycler',
            fields=[
                ('id_recycler', models.AutoField(primary_key=True, serialize=False)),
                ('recycler_name', models.CharField(max_length=100)),
                ('recycler_description', models.CharField(max_length=255)),
                ('recycler_image', models.CharField(max_length=255)),
                ('recycler_number', models.IntegerField()),
                ('recycler_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_rating', models.FloatField(default=0)),
                ('supplier_address', models.CharField(max_length=100)),
                ('supplier_state', models.CharField(max_length=50)),
                ('supplier_city', models.CharField(max_length=50)),
                ('supplier_zip_code', models.CharField(max_length=10)),
                ('supplier_company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('id_supplier_account', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_email', models.CharField(max_length=100)),
                ('supplier_password', models.CharField(max_length=100)),
                ('supplier_phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('client_firstname', models.CharField(max_length=50)),
                ('client_lastname', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=20)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.clientaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False)),
                ('client_address', models.CharField(max_length=100)),
                ('client_city', models.CharField(max_length=50)),
                ('client_state', models.CharField(max_length=50)),
                ('client_zip_code', models.CharField(max_length=10)),
                ('client_address_additional_information', models.CharField(max_length=100)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.clientaddress')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal')], max_length=20)),
                ('payment_amount', models.FloatField()),
                ('payment_date', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id_order_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_purchase', models.FloatField()),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.order')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id_shipment', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_tracking_number', models.CharField(max_length=50)),
                ('shipment_carrier', models.CharField(max_length=50)),
                ('shipment_status', models.CharField(max_length=50)),
                ('shipment_date', models.DateTimeField()),
                ('shipment_estimated_delivery_date', models.DateTimeField()),
                ('shipment_actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id_cart', models.AutoField(primary_key=True, serialize=False)),
                ('cart_product_quantity', models.IntegerField(default=1)),
                ('cart_added_date', models.DateTimeField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.client')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='id_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='id_supplier_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.supplieraccount'),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id_reset', models.AutoField(primary_key=True, serialize=False)),
                ('reset_code', models.CharField(max_length=10)),
                ('reset_expiration_time', models.DateTimeField()),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CitasApp.clientaccount')),
                ('id_supplier_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CitasApp.supplieraccount')),
            ],
        ),
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id_wish', models.AutoField(primary_key=True, serialize=False)),
                ('wish_date_added', models.DateTimeField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.client')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasApp.product')),
            ],
        ),
    ]
